version: '3'
services:
  service1:
    image: webservice-user:latest
    # Autres configurations pour le service 1
    ports:
    - "3001:3001"
  service2:
    image: webservice-movie:latest
    # Autres configurations pour le service 2
    ports:
    - "3000:3000"
  service3:
    image: webservice-cinema:latest
    # Autres configurations pour le service 3
    ports:
    - "3003:3003"
  service4:
    image: webservice-reservation:latest
    # Autres configurations pour le service 4
    ports:
    - "3002:3002"
  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672" # Port pour AMQP
        - "15672:15672" # Port pour l'interface de gestion Web
      hostname: rabbitmq # Nom d'hôte du conteneur RabbitMQ